### ISSUE TITLE
Project is not setting up using docker compose

### ISSUE THREAD

**Issue by jaymahakal1** [IliaMalafeev/BookStore_FullStack#1]
Hi!
I am trying to run this app locally by using ur docker compose file while running it is showing me this error
Can u tell me how should i correct it?
<img width="1351" alt="Screenshot 2024-04-28 at 3 43 14 PM" src="https://github.com/IliaMalafeev/BookStore_FullStack/assets/115314474/9978a9c1-d990-4f7f-85f4-e5c8fedbf351">

**Comment by IliaMalafeev** [comment]
Hi, @jaymahakal1 !

I've been playing with tests lately within the project and have added 'application.properties.blank' file to the 'src/test/resources' folder of Backend application package. I think if you would remove '.blank' part, same as for the main properties file, and fill out the 'jwt_secret' field with your value here as well, then it should start working as expected.

Sorry for the inconvenience, I will surely update the readme instructions once I'm done implementing test classes.

Hope that helps and sorry for the late response! Feel free to ask me more if you encounter any further problems, cheers!

**Comment by jaymahakal1** [comment]
Yeah!.....
Thanks for replying dude.
